version: '{build}'
environment:
  NODE_VERSION: "10"
  NPM_TOKEN:
    secure: Xcfvwit/+0KAyunoSBZZ0Fh6edpi0P4xhBkH01nt+Y8WQI5VEfiniA3+Kal2XH9S
install:
- ps: >-
    $ErrorActionPreference = "SilentlyContinue"
    
    Install-Product node $env:NODE_VERSION
    
    & npm install -g npm 2>&1
    
    & npm install 2>&1
    
    trap { "Error: $_" }
    
    $LastExitCode = 0
    
    & npm --version
build: none
test_script:
- cmd: npm test
deploy_script:
- cmd: >-
    echo //registry.npmjs.org/:_authToken=%NPM_TOKEN%> .npmrc

    node --version
        
    if %APPVEYOR_REPO_BRANCH% equ master npm publish
