version: '{build}'
environment:
  NODE_VERSION: "10"
  NPM_TOKEN:
    secure: Zl+/rT2jbEm0NQhWC0YDV/fY8i/EYBYCd821ZXe9xgGVmQOG45wyBrZH4whkdjHs
install:
- ps: >-
    $ErrorActionPreference = "SilentlyContinue"
    
    Install-Product node $env:NODE_VERSION
    
    & npm install -g npm 2>&1
    
    & npm install 2>&1
    
    trap { "Error: $_" }
    
    $LastExitCode = 0
    
    & npm --version
build: none
test_script:
- cmd: npm test
deploy_script:
- cmd: >-
    echo //registry.npmjs.org/:_authToken=%NPM_TOKEN%> .npmrc

    node --version
        
    if %APPVEYOR_REPO_BRANCH% equ main npm publish
